export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_CRAFTER = 'GET_CRAFTER';
export const CRAFTER_LOADING = 'CRAFTER_LOADING';
export const CRAFTER_NOT_FOUND = 'CRAFTER_NOT_FOUND';
export const CLEAR_CURRENT_CRAFTER = 'CLEAR_CURRENT_CRAFTER';
export const GET_CURRENT_CRAFTER = 'GET_CURRENT_CRAFTER';
export const GET_ALL_CRAFTERS = 'GET_ALL_CRAFTERS';
export const GET_EVENTS = 'GET_EVENTS';
export const EVENT_LOADING = 'EVENT_LOADING';
export const GET_CRAFTER_FROM_HANDLE = 'GET_CRAFTER_FROM_HANDLE';
